name: e2e_macos
description: Temporary desktop implmentation of e2e from flutter/plugins
version: 0.0.1
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/e2e/e2e_macos

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: E2EPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
