name: shared_preferences
description: Flutter plugin for reading and writing simple key-value pairs.
  Wraps NSUserDefaults on iOS and SharedPreferences on Android.
homepage: https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences
version: 0.5.7

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.sharedpreferences
        pluginClass: SharedPreferencesPlugin
      ios:
        pluginClass: FLTSharedPreferencesPlugin
      macos:
        default_package: shared_preferences_macos
      web:
        default_package: shared_preferences_web
      windows:
        default_package: shared_preferences_windows

dependencies:
  meta: ^1.0.4
  flutter:
    sdk: flutter
  platform: 2.2.1
  shared_preferences_platform_interface:
  shared_preferences_macos:
  shared_preferences_web:
  shared_preferences_windows:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.2.0
  pedantic: ^1.8.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
